// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBabVzqom4f5OkqWIrHQCqQNSRmpZN3fHI',
    appId: '1:706981548105:web:d1e8977fe611cfdd9d6f98',
    messagingSenderId: '706981548105',
    projectId: 'rentatouille-25891',
    authDomain: 'rentatouille-25891.firebaseapp.com',
    storageBucket: 'rentatouille-25891.appspot.com',
    measurementId: 'G-3WDFDJJFLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkjH7fQToZBvHVox2eKSbpWnXPWlneYZ8',
    appId: '1:706981548105:android:cc04615a41268d409d6f98',
    messagingSenderId: '706981548105',
    projectId: 'rentatouille-25891',
    storageBucket: 'rentatouille-25891.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9TdH1q2e3gq3qiszceAw9FnI_NV6OI1c',
    appId: '1:706981548105:ios:a9f5ac3f443246bf9d6f98',
    messagingSenderId: '706981548105',
    projectId: 'rentatouille-25891',
    storageBucket: 'rentatouille-25891.appspot.com',
    iosBundleId: 'com.example.rentatouille',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9TdH1q2e3gq3qiszceAw9FnI_NV6OI1c',
    appId: '1:706981548105:ios:ac739c10c4bba9399d6f98',
    messagingSenderId: '706981548105',
    projectId: 'rentatouille-25891',
    storageBucket: 'rentatouille-25891.appspot.com',
    iosBundleId: 'com.example.rentatouille.RunnerTests',
  );
}
